services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    image: node:24_alpine_express
    container_name: container_node
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - PORT=3000
    networks:
      network_node:
        ipv4_address: 172.16.0.11

  database:
    image: mysql:8.4.5
    container_name: container_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      network_node:
        ipv4_address: 172.16.0.12

  adminer:
    image: adminer:5-standalone
    container_name: container_adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      network_node:
        ipv4_address: 172.16.0.13

networks:
  network_node:
    name: global_node
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24